language: java
sudo: false
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
script: mvn clean install -f jdcallgraph/pom.xml

after_success:
  - mvn clean cobertura:cobertura coveralls:report -f jdcallgraph/pom.xml
