language: java
sudo: false
dist: trusty
jdk:
- openjdk8
- oraclejdk8

before_script:
- cd jdcallgraph
script: mvn clean install
after_success:
- mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: releases
  api_key:
    secure: QZgKETGGH7p8Fco9sOllhWdAciqYi79qGXBD6mhp59wkxNts3e3pRTuxOpI1N+HrJ8Ilyci+kkOyQu90Wh0/F0Oi/KOdDMmfhmaUcOdrPrC1A6S2eJR1pcZ4jagKbva1yu7Xd3jYScdRU4nFVe/anoQPbCx6aQSK5unrjZOpbnS0WlTWwP5x0EPaQ2bnpVycbqVUth6kdqSXkyE9CJc2MwQRpDNl6z+5O8C4q+HKx8VBhRumFSkFLXItpN0nsuR+aA3UNTcb/xOJieAOEy35ORQKBtpAsILex9T1BH66apm9y9Js8xoo/pLuyGQSBBRekwc2GpePWHlPIlCGXBuNbblWDqZCaobvEgB+Q8O/e/cpu1XhtG0dFHZ6rsqcyrsVScTm5Q9QdttGeq/hegNlWyW5rK4p+Mb31v0sFCsBejB1ytWbgiBZ66aZvJF8EwW8tnyVA9jRsUyomRIOb1FH3DKYKtIji00VlIDz14yb9Wt5SlDAiACQmSn8OjG4jByRFCp+lqnJdqdn9CYc81nMrL8DFubw3hUpoQ6jpZrM42krcc7ccv1YRQ9566M7iB8vey1vSEfNBnfeO2m/q+AVDNDDQLC0GHeRXGVVAhVTkfOWkXiDpPQ8jIYVs2a6UNupkEXB/Bw1KuUGR3X2kRwrifDAk4q3SOYqr5gHkVebJWs=
  skip_cleanup: true
  file_glob: true
  file: jdcallgraph-*-agent.jar
  on:
    tags: true
    repo: dkarv/jdcallgraph
    jdk: 'openjdk8'
