version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    fast_finish: true
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
install:
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - cd jdcallgraph
  - mvn clean verify
  - cd ..\integration_tests
  - all.bat
cache:
  - C:\maven\ -> appveyor.yml
  - C:\Users\appveyor\.m2\ -> pom.xml
